import turtle
def MAP(side):
    t=turtle.Turtle()
    t.up()
    t.forward(5*side)
    t.down()
    t.left(90)
    t.forward(5*side)
    t.left(90)
    t.write('MAP OF ACCRA')
    t.forward(14*side)
    t.left(90)
    t.forward(10*side)
    t.left(90)
    t.forward(14*side)
    t.left(90)
    t.forward(6*side)
    t.left(90)
    t.forward(3*side)
    t.write('ROAD TO ABURI')
    t.forward(side)
    t.right(90)
    t.forward(40 + side)
    t.left(45)
    t.color('red')
    t.begin_fill()
    t.left(90)
    t.write('ASHESI UNIVERSITY - BEREKUSO')
    for i in range(4):
        t.forward(side-10)
        t.right(90)
    t.end_fill()
    t.color('black')
    t.forward(165)
    t.right(45)
    t.forward(side)
    t.color('green')
    t.begin_fill()
    t.left(90)
    t.write('LEGON')
    for i in range(4):
        t.forward(side+15)
        t.right(90)
    t.end_fill()
    t.color('black')
    t.backward((4*side)+20)
    t. write('ROAD TO KUMASI')
    t.forward(side+40)
    t.right(90)
    t.forward(side+20)
    t.color('blue')
    t.begin_fill()
    t.left(90)
    t.write('PENTU.SOTUOM')
    for i in range(4):
        t.forward(side-10)
        t.right(90)
    t.end_fill()
    t.color('black')
    t.right(90)
    t.forward(side+30)
    t.left(90)
    t.forward(5*side)
    t.right(45)
    t.forward(5*side)
    t.write('ROAD TO WINNNEBA')
    t.backward(6*side)
    t.left(90)
    t.forward(2*side)
    t.color('yellow')
    t.begin_fill()
    t.left(90)
    t.write('ACCRA POLY')
    for i in range(4):
        t.forward(side+10)
        t.left(90)
    t.end_fill()
    t.color('black')
    t.right(45)
    t.forward(9*side)
    t.write('ROAD TO TEMA')
    t.backward(6*side)
    t.left(90)
    t.forward(side+40)
    t.color('orange')
    t.begin_fill()
    t.left(90)
    t.write('UPS')
    for i in range(4):
        t.forward(side-15)
        t.left(90)
    t.end_fill()
    t.color('black')
    t.right(45)
    t.forward(2*side)
    t.left(135)
    t.forward(5.5*side)
    t.write('ROAD TO BEACH')
    t.left(90)
    t.forward(3*side)
    t.color('violet')
    t.begin_fill()
    t.left(90)
    t.write('KOTOKA AIRPORT')
    for i in range(4):
        t.forward(side+30)
        t.left(90)
    t.end_fill()
    t.color('black')
    t.forward(5.5*side)
    t.color('cyan')
    t.begin_fill()
    t.left(90)
    t.write('ACCRA MALL')
    for i in range(4):
        t.forward(side-20)
        t.left(90)
    t.end_fill()
    t.color('black')
    t.forward(3*side)
    t.up()
    t.right(90)
    t.forward(9*side)
    
    
MAP(60)

    
    
    
    
    
